dataset_paths = {
    "celeba_train": "",
    "celeba_test": "",
    "celeba_train_sketch": "",
    "celeba_test_sketch": "",
    "celeba_train_segmentation": "",
    "celeba_test_segmentation": "",
    "ffhq": "",
    "portraits_train": "/content/drive/MyDrive/portrait_data/small_images/train",
    "portraits_val": "/content/drive/MyDrive/portrait_data/small_images/val",
    "paired_gens_input": "/content/drive/MyDrive/Colab_Notebooks/baldurs_gan/stylegan2_outputs/paired_images/input",
    "paired_gens_output": "/content/drive/MyDrive/Colab_Notebooks/baldurs_gan/stylegan2_outputs/paired_images/output",
    "paired_gens_latents": "/content/drive/MyDrive/Colab_Notebooks/baldurs_gan/stylegan2_outputs/paired_images/latents",
    "paired_gens_val_input": "/content/drive/MyDrive/Colab_Notebooks/baldurs_gan/stylegan2_outputs/paired_images/input_val",
    "paired_gens_val_output": "/content/drive/MyDrive/Colab_Notebooks/baldurs_gan/stylegan2_outputs/paired_images/output_val",
    "paired_gens_val_latents": "/content/drive/MyDrive/Colab_Notebooks/baldurs_gan/stylegan2_outputs/paired_images/latents_val",
    "ffhq_512": "/content/ffhq_512/",
    "ffhq_512_val": "/content/ffhq_512_val",
    "ffhq_512_cond": "/content/ffhq_512_trimmed/",
    "ffhq_512_cond_val": "/content/ffhq_512_filtered",
    "ffhq_512_labels": "/content/ffhq_512_filtered/dataset.json",
}

model_paths = {
    "stylegan_ffhq": "/content/pretrained_models/stylegan2-ffhq-config-f.pt",
    "ir_se50": "/content/pretrained_models/model_ir_se50.pth",
    "circular_face": "/content/pretrained_models/CurricularFace_Backbone.pth",
    "mtcnn_pnet": "/content/pretrained_models/mtcnn/pnet.npy",
    "mtcnn_rnet": "/content/pretrained_models/mtcnn/rnet.npy",
    "mtcnn_onet": "/content/pretrained_models/mtcnn/onet.npy",
    "shape_predictor": "/content/shape_predictor_68_face_landmarks.dat",
}
